// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAls6hEEdbweNynBBgY7Wr7yyftOm-tmbI',
    appId: '1:906556867299:web:e7480f7187fc6ff219bbd6',
    messagingSenderId: '906556867299',
    projectId: 'ecommerceapp-c8c0e',
    authDomain: 'ecommerceapp-c8c0e.firebaseapp.com',
    storageBucket: 'ecommerceapp-c8c0e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLrm7aqmA5Or505_INszgnDcaJg-X_vFI',
    appId: '1:906556867299:android:050da25c492c4b8219bbd6',
    messagingSenderId: '906556867299',
    projectId: 'ecommerceapp-c8c0e',
    storageBucket: 'ecommerceapp-c8c0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTBeeHwxmT0x7_j57J4K__3lSX1rhVNaE',
    appId: '1:906556867299:ios:5cc325d7ac25273319bbd6',
    messagingSenderId: '906556867299',
    projectId: 'ecommerceapp-c8c0e',
    storageBucket: 'ecommerceapp-c8c0e.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTBeeHwxmT0x7_j57J4K__3lSX1rhVNaE',
    appId: '1:906556867299:ios:5cc325d7ac25273319bbd6',
    messagingSenderId: '906556867299',
    projectId: 'ecommerceapp-c8c0e',
    storageBucket: 'ecommerceapp-c8c0e.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAls6hEEdbweNynBBgY7Wr7yyftOm-tmbI',
    appId: '1:906556867299:web:5e74ca86c17e152019bbd6',
    messagingSenderId: '906556867299',
    projectId: 'ecommerceapp-c8c0e',
    authDomain: 'ecommerceapp-c8c0e.firebaseapp.com',
    storageBucket: 'ecommerceapp-c8c0e.firebasestorage.app',
  );
}
